AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'bin/**/*'
Documentation:
  Enabled: false
LineLength:
  Enabled: true
  Max: 120
MethodLength:
  Max: 20
IndentHash:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
